import card1 from "./card1.png";
import card2 from "./card2.png";
import flex from "./flex.png";
import header from "./header.png";
import investmobile from "./InvestMobile.png";
import logoBlack from "./logoBlack.svg";
import logoWhite from "./logoWhite.svg";
import piggy from "./piggy.png";
import rect from "./rect.png";
import safelock from "./safelock.png";
import security from "./security.png";
import target from "./target.png";
import techcrunch from "./TechCrunch.png";
import techpoint from "./TechPoint.png";
import theguardian from "./TheGuardian.png";
import saver from "./saver.jpeg";

export const Card1 = card1;
export const Card2 = card2;
export const Flex = flex;
export const Header = header;
export const InvestMobile = investmobile;
export const LogoBlack = logoBlack;
export const LogoWhite = logoWhite;
export const Piggy = piggy;
export const Rect = rect;
export const Safelock = safelock;
export const Security = security;
export const Target = target;
export const TechCrunch = techcrunch;
export const TechPoint = techpoint;
export const TheGuardian = theguardian;
export const Saver = saver;
